version: "3.5"
services:
  nginx-proxy:
    user: root
    image: jwilder/nginx-proxy
    volumes:
      - ./config/htpasswd:/etc/nginx/htpasswd:rw
      - /var/run/docker.sock:/tmp/docker.sock:ro
    ports:
      - "80:80"
      - "443:443"
    expose:
      - "80"
      - "443"
    restart: always
    networks:
      - deploy_net
    labels:
      role: proxy

networks:
  deploy_net:
    external:
      name: dockernet
