version: "3.5"
services:
  letsencrypt-nginx-proxy-companion:
    user: root
    image: jrcs/letsencrypt-nginx-proxy-companion
    volumes_from:
      - nginx-proxy
    volumes:
      - ./config/certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart_policy: always
    networks:
      - deploy_net
    labels:
      role: proxy

networks:
  deploy_net:
    external:
    name: dockernet